### ISSUE TITLE
npm install with errors

### ISSUE THREAD

**Issue by purist1337** [kesaloh13/vlcdweb#7]
I tried to install the software, but it's not working. Please find the error log attached.

Thanks
[vlcdweb_failed_install.txt](https://github.com/kesaloh13/vlcdweb/files/332993/vlcdweb_failed_install.txt)

**Comment by kesaloh13** [comment]
Updated packages. Now it should run on windows. Tested with Windows 10, 64bit / Node 4.4.6.
